# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ZipcodeHackathon' do
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'
  use_frameworks!
  
  pod 'Alamofire', '~> 3.0'
end

target 'ZipcodeHackathonTests' do

end

target 'ZipcodeHackathonUITests' do

end

